services:

  backend:
    pull_policy: never
    build: ./backend/
    container_name: fastapi-backend
    ports:
      - "8000:8000"

  frontend:
    pull_policy: never
    container_name: nginx-frontend
    image: "nginx:latest"
    ports:
      - "80:80"

  db:
    pull_policy: never
    restart: always
    container_name: postgre-db
    build: ./db
    ports:
      - "8080:8080"
    env_file:
      - ./postgre/.env
    volumes:
      - db/data

volumes:
  postgredb-data:
