services:

  backend:
    container_name: fastapi-backend
    pull_policy: never
    build: ./backend/
    depends_on:
      - db
    ports:
      - ${APP_HOST_PORT}:8000
    env_file:
      - ./backend/.env

  frontend:
    container_name: nginx-frontend
    pull_policy: never
    build: ./frontend
    ports:
      - ${NGINX_HOST_PORT}:80
    env_file:
      - ./frontend/.env

  db:
    container_name: postgre-db
    pull_policy: never
    restart: always
    build: ./db
    ports:
      - ${DB_HOST_PORT}:5432
    env_file:
      - ./db/.env
    volumes:
      - postgredb-data:/db/data

volumes:
  postgredb-data:
