services:

  backend:
    container_name: fastapi-backend
    pull_policy: never
    build: ./backend/
    depends_on:
        db:
          condition: service_healthy
          restart: true
    ports:
      - ${APP_HOST_PORT}:8000
    env_file:
      - ./backend/.env
      - ./db/.env
      - ./.env

  frontend:
    container_name: nginx-frontend
    pull_policy: never
    build: ./frontend
    ports:
      - ${NGINX_HOST_PORT}:80
    env_file:
      - ./frontend/.env

  db:
    container_name: postgre-db
    pull_policy: never
    restart: always
    build: ./db
    ports:
      - ${DB_HOST_PORT}:5432
    env_file:
      - ./db/.env
    volumes:
      - postgredb-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  postgredb-data:
