services:

  backend:
    container_name: fastapi-backend
    pull_policy: never
    build: ./backend/
    depends_on:
        db:
          condition: service_healthy
          restart: true
    expose:
      - ${APP_PORT}
    ports:
      - ${APP_HOST_PORT}:${APP_PORT}
    env_file:
      - ./.env
    stdin_open: true # docker run -i DEBUG PURPOSE
    tty: true        # docker run -t DEBUG PURPOSE

  frontend:
    container_name: nginx-frontend
    pull_policy: never
    build: ./frontend
    expose:
      - ${NGINX_PORT}
    ports:
      - ${NGINX_HOST_PORT}:${NGINX_PORT}
    env_file:
      - ./.env

  db:
    container_name: ${DB_NAME}
    pull_policy: never
    restart: always
    build: ./db
    expose:
      - ${DB_PORT}
    ports:
      - ${DB_HOST_PORT}:${DB_PORT}
    env_file:
      - ./.env
    volumes:
      - postgredb-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  postgredb-data:
