services:

  backend:
    container_name: fastapi-backend
    pull_policy: never
    build: ./backend/
    depends_on:
      - db
    ports:
      - "8000:8000"
    end_file:
      - ./backend/.env

  frontend:
    container_name: nginx-frontend
    pull_policy: never
    image: ./frontend
    ports:
      - "80:80"

  db:
    container_name: postgre-db
    pull_policy: never
    restart: always
    build: ./db
    ports:
      - "8080:5432"
    env_file:
      - ./db/.env
    volumes:
      - postgredb-data:/db/data

volumes:
  postgredb-data:
